name: omnis_env
channels:
  - conda-forge 
  - defaults
dependencies:
  - python=3.12
  - pydub
  - pip
  - pip:
      - annotated-types
      - anyio
      - certifi
      - click
      - distro
      - h11
      - httpcore
      - httpx
      - idna
      - jiter
      - openai
      - pydantic
      - pydantic-core
      - python-dotenv
      - setuptools
      - sniffio
      - tqdm
      - typing-extensions
      - wheel